In [6]:
import pandas as pd

In [7]:
dataset = pd.read_csv("target_tabungan.csv")

In [8]:
dataset.head()

,tanggal,nama_target_id,nama_target,jumlah_target,nabung_harian,jumlah_terkumpul,progres,sisa_target,status_id,status
0,01/01/2022,0,Iphone 17 Pro Max,25000000,300000,300000,0.01,0.99,0,BELUM TERPENUHI
1,01/02/2022,0,Iphone 17 Pro Max,25000000,500000,800000,0.03,0.97,0,BELUM TERPENUHI
2,01/03/2022,0,Iphone 17 Pro Max,25000000,200000,1000000,0.04,0.96,0,BELUM TERPENUHI
3,01/04/2022,0,Iphone 17 Pro Max,25000000,500000,1500000,0.06,0.94,0,BELUM TERPENUHI
4,01/05/2022,0,Iphone 17 Pro Max,25000000,500000,2000000,0.08,0.92,0,BELUM TERPENUHI

In [9]:
dataset['tanggal'] = pd.to_datetime(dataset['tanggal'])

finish_dates = (
    dataset[dataset['status_id'] == 1]
    .groupby('nama_target_id')['tanggal']
    .max()
)

dataset['finish_date'] = dataset['nama_target_id'].map(finish_dates)

dataset['remaining_days'] = (
    dataset['finish_date'] - dataset['tanggal']
).dt.days

df = dataset[['tanggal', 'jumlah_target', 'nabung_harian', 'jumlah_terkumpul', 'status_id', 'remaining_days']].copy()
df

,tanggal,jumlah_target,nabung_harian,jumlah_terkumpul,status_id,remaining_days
0,2022-01-01,25000000,300000,300000,0,106
1,2022-01-02,25000000,500000,800000,0,105
2,2022-01-03,25000000,200000,1000000,0,104
3,2022-01-04,25000000,500000,1500000,0,103
4,2022-01-05,25000000,500000,2000000,0,102
...,...,...,...,...,...,...
1206,2025-04-21,8000000,300000,6750000,0,4
1207,2025-04-22,8000000,200000,6950000,0,3
1208,2025-04-23,8000000,100000,7050000,0,2
1209,2025-04-24,8000000,500000,7550000,0,1
1210,2025-04-25,8000000,500000,8050000,1,0

In [10]:
from sklearn.model_selection import train_test_split

X = df[
    [
        'jumlah_target',
        'nabung_harian',
        'jumlah_terkumpul'
    ]
]

y = df['remaining_days']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

inputs = tf.keras.Input(shape=(X_train.shape[1],))

x = Dense(128, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
x = Dense(32, activation='relu')(x)

outputs = Dense(1)(x)

model = Model(inputs, outputs)

model.compile(
    optimizer='adam',
    loss='mae',
    metrics=['mae']
)

In [13]:
class StopAtMAE(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        mae = logs.get('mae')

        if mae < 0.03:
            self.model.stop_training = True

In [14]:
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[StopAtMAE()]
)

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 55.1872 - mae: 55.1872 - val_loss: 56.1672 - val_mae: 56.1672
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 51.4212 - mae: 51.4212 - val_loss: 48.8222 - val_mae: 48.8222
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 42.8090 - mae: 42.8090 - val_loss: 36.1828 - val_mae: 36.1828
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.8555 - mae: 28.8555 - val_loss: 17.2140 - val_mae: 17.2140
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.3505 - mae: 15.3505 - val_loss: 10.6056 - val_mae: 10.6056
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.0726 - mae: 10.0726 - val_loss: 8.5061 - val_mae: 8.5061
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2269 - mae: 8.2269 - val_loss: 7.3642 - val_mae: 7.3642
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.9412 - mae: 6.9412 - val_loss: 6.5267 - val_mae: 6.5267
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.8548 - mae: 5.8548 - val_loss: 5.3944 - val_mae: 5.3944
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.9936 - mae: 4.9936 - val_loss: 4.7934 - val_mae: 4.7934
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3400 - mae: 4.3400 - val_loss: 4.0390 - val_mae: 4.0390
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.7413 - mae: 3.7413 - val_loss: 3.6652 - val_mae: 3.6652
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5700 - mae: 3.5700 - val_loss: 3.9137 - val_mae: 3.9137
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.6492 - mae: 3.6492 - val_loss: 3.4280 - val_mae: 3.4280
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.3428 - mae: 3.3428 - val_loss: 3.4028 - val_mae: 3.4028
Epoch 16/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.2771 - mae: 3.2771 - val_loss: 3.4867 - val_mae: 3.4867
Epoch 17/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.2577 - mae: 3.2577 - val_loss: 3.2080 - val_mae: 3.2080
Epoch 18/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.0923 - mae: 3.0923 - val_loss: 3.1870 - val_mae: 3.1870
Epoch 19/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.1232 - mae: 3.1232 - val_loss: 3.1256 - val_mae: 3.1256
Epoch 20/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.0193 - mae: 3.0193 - val_loss: 3.2289 - val_mae: 3.2289
Epoch 21/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.9817 - mae: 2.9817 - val_loss: 3.1559 - val_mae: 3.1559
Epoch 22/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.9738 - mae: 2.9738 - val_loss: 3.0962 - val_mae: 3.0962
Epoch 23/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.0635 - mae: 3.0635 - val_loss: 3.0756 - val_mae: 3.0756
Epoch 24/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.9804 - mae: 2.9804 - val_loss: 3.2686 - val_mae: 3.2686
Epoch 25/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.0138 - mae: 3.0138 - val_loss: 3.1014 - val_mae: 3.1014
Epoch 26/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8710 - mae: 2.8710 - val_loss: 3.3445 - val_mae: 3.3445
Epoch 27/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.9030 - mae: 2.9030 - val_loss: 3.1831 - val_mae: 3.1831
Epoch 28/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8555 - mae: 2.8555 - val_loss: 3.0067 - val_mae: 3.0067
Epoch 29/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8531 - mae: 2.8531 - val_loss: 2.9859 - val_mae: 2.9859
Epoch 30/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9066 - mae: 2.9066 - val_loss: 2.9874 - val_mae: 2.9874
Epoch 31/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8762 - mae: 2.8762 - val_loss: 2.9903 - val_mae: 2.9903
Epoch 32/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7670 - mae: 2.7670 - val_loss: 3.2445 - val_mae: 3.2445
Epoch 33/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.7905 - mae: 2.7905 - val_loss: 3.1839 - val_mae: 3.1839
Epoch 34/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8643 - mae: 2.8643 - val_loss: 3.2941 - val_mae: 3.2941
Epoch 35/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.9033 - mae: 2.9033 - val_loss: 3.4197 - val_mae: 3.4197
Epoch 36/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8713 - mae: 2.8713 - val_loss: 3.0556 - val_mae: 3.0556
Epoch 37/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.7610 - mae: 2.7610 - val_loss: 3.0207 - val_mae: 3.0207
Epoch 38/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.8039 - mae: 2.8039 - val_loss: 3.0732 - val_mae: 3.0732
Epoch 39/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.8124 - mae: 2.8124 - val_loss: 3.0142 - val_mae: 3.0142
Epoch 40/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.7791 - mae: 2.7791 - val_loss: 2.9495 - val_mae: 2.9495
Epoch 41/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.7674 - mae: 2.7674 - val_loss: 3.2075 - val_mae: 3.2075
Epoch 42/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7803 - mae: 2.7803 - val_loss: 3.2211 - val_mae: 3.2211
Epoch 43/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7185 - mae: 2.7185 - val_loss: 2.9704 - val_mae: 2.9704
Epoch 44/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7526 - mae: 2.7526 - val_loss: 2.9630 - val_mae: 2.9630
Epoch 45/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6922 - mae: 2.6922 - val_loss: 3.1412 - val_mae: 3.1412
Epoch 46/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7626 - mae: 2.7626 - val_loss: 2.9852 - val_mae: 2.9852
Epoch 47/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7192 - mae: 2.7192 - val_loss: 2.9836 - val_mae: 2.9836
Epoch 48/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8167 - mae: 2.8167 - val_loss: 2.9566 - val_mae: 2.9566
Epoch 49/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7296 - mae: 2.7296 - val_loss: 2.9429 - val_mae: 2.9429
Epoch 50/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8173 - mae: 2.8173 - val_loss: 2.9744 - val_mae: 2.9744
Epoch 51/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8723 - mae: 2.8723 - val_loss: 3.2808 - val_mae: 3.2808
Epoch 52/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7973 - mae: 2.7973 - val_loss: 3.1396 - val_mae: 3.1396
Epoch 53/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8043 - mae: 2.8043 - val_loss: 2.9010 - val_mae: 2.9010
Epoch 54/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7609 - mae: 2.7609 - val_loss: 2.9288 - val_mae: 2.9288
Epoch 55/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6865 - mae: 2.6865 - val_loss: 3.0324 - val_mae: 3.0324
Epoch 56/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7153 - mae: 2.7153 - val_loss: 3.0230 - val_mae: 3.0230
Epoch 57/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6899 - mae: 2.6899 - val_loss: 2.9895 - val_mae: 2.9895
Epoch 58/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7510 - mae: 2.7510 - val_loss: 3.0413 - val_mae: 3.0413
Epoch 59/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6780 - mae: 2.6780 - val_loss: 2.9919 - val_mae: 2.9919
Epoch 60/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6459 - mae: 2.6459 - val_loss: 2.8804 - val_mae: 2.8804
Epoch 61/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6936 - mae: 2.6936 - val_loss: 3.0800 - val_mae: 3.0800
Epoch 62/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7094 - mae: 2.7094 - val_loss: 3.0132 - val_mae: 3.0132
Epoch 63/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6247 - mae: 2.6247 - val_loss: 3.0173 - val_mae: 3.0173
Epoch 64/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6148 - mae: 2.6148 - val_loss: 2.8966 - val_mae: 2.8966
Epoch 65/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6632 - mae: 2.6632 - val_loss: 2.9727 - val_mae: 2.9727
Epoch 66/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6605 - mae: 2.6605 - val_loss: 2.9568 - val_mae: 2.9568
Epoch 67/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7053 - mae: 2.7053 - val_loss: 3.0791 - val_mae: 3.0791
Epoch 68/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6273 - mae: 2.6273 - val_loss: 2.9085 - val_mae: 2.9085
Epoch 69/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5797 - mae: 2.5797 - val_loss: 2.8764 - val_mae: 2.8764
Epoch 70/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6820 - mae: 2.6820 - val_loss: 2.9444 - val_mae: 2.9444
Epoch 71/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6574 - mae: 2.6574 - val_loss: 2.8340 - val_mae: 2.8340
Epoch 72/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5984 - mae: 2.5984 - val_loss: 2.9948 - val_mae: 2.9948
Epoch 73/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5766 - mae: 2.5766 - val_loss: 2.8658 - val_mae: 2.8658
Epoch 74/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6677 - mae: 2.6677 - val_loss: 2.9173 - val_mae: 2.9173
Epoch 75/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5692 - mae: 2.5692 - val_loss: 2.8120 - val_mae: 2.8120
Epoch 76/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5738 - mae: 2.5738 - val_loss: 2.8284 - val_mae: 2.8284
Epoch 77/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5996 - mae: 2.5996 - val_loss: 2.8091 - val_mae: 2.8091
Epoch 78/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5267 - mae: 2.5267 - val_loss: 2.9209 - val_mae: 2.9209
Epoch 79/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5531 - mae: 2.5531 - val_loss: 2.9254 - val_mae: 2.9254
Epoch 80/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5999 - mae: 2.5999 - val_loss: 2.8906 - val_mae: 2.8906
Epoch 81/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5620 - mae: 2.5620 - val_loss: 2.8629 - val_mae: 2.8629
Epoch 82/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5376 - mae: 2.5376 - val_loss: 2.8282 - val_mae: 2.8282
Epoch 83/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5282 - mae: 2.5282 - val_loss: 2.7641 - val_mae: 2.7641
Epoch 84/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5386 - mae: 2.5386 - val_loss: 2.9935 - val_mae: 2.9935
Epoch 85/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5546 - mae: 2.5546 - val_loss: 2.8250 - val_mae: 2.8250
Epoch 86/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6707 - mae: 2.6707 - val_loss: 2.7589 - val_mae: 2.7589
Epoch 87/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5002 - mae: 2.5002 - val_loss: 2.7868 - val_mae: 2.7868
Epoch 88/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5016 - mae: 2.5016 - val_loss: 2.8389 - val_mae: 2.8389
Epoch 89/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5287 - mae: 2.5287 - val_loss: 2.8759 - val_mae: 2.8759
Epoch 90/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5078 - mae: 2.5078 - val_loss: 2.7763 - val_mae: 2.7763
Epoch 91/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5205 - mae: 2.5205 - val_loss: 2.7298 - val_mae: 2.7298
Epoch 92/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4984 - mae: 2.4984 - val_loss: 2.7538 - val_mae: 2.7538
Epoch 93/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5010 - mae: 2.5010 - val_loss: 2.9288 - val_mae: 2.9288
Epoch 94/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4729 - mae: 2.4729 - val_loss: 2.7594 - val_mae: 2.7594
Epoch 95/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4666 - mae: 2.4666 - val_loss: 2.7622 - val_mae: 2.7622
Epoch 96/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5180 - mae: 2.5180 - val_loss: 2.8521 - val_mae: 2.8521
Epoch 97/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6466 - mae: 2.6466 - val_loss: 2.7312 - val_mae: 2.7312
Epoch 98/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5721 - mae: 2.5721 - val_loss: 2.7654 - val_mae: 2.7654
Epoch 99/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4811 - mae: 2.4811 - val_loss: 2.7186 - val_mae: 2.7186
Epoch 100/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5193 - mae: 2.5193 - val_loss: 2.7707 - val_mae: 2.7707

In [15]:
loss, mae = model.evaluate(X_test, y_test)

print("MAE:", mae)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6712 - mae: 2.6712
MAE: 2.671191692352295

In [16]:
pred = model.predict(X_test)

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': pred.flatten()
})

comparison.head(10)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

   Actual   Predicted
0       5    6.432436
1     131  129.692749
2      19   20.822378
3     129  126.234795
4      30   30.361732
5      55   54.213940
6      21   21.473082
7      57   58.043507
8      38   35.466488
9      40   43.012562

In [17]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, pred)

print("R2 Score:", r2)

R2 Score: 0.9895896911621094

Inference

In [18]:
new_data = pd.DataFrame({
    'jumlah_target': [28000000],
    'nabung_harian': [100000],
    'jumlah_terkumpul': [1000000],
})

new_data_scaled = scaler.transform(new_data)

prediction = model.predict(new_data_scaled)

prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

array([[125.43382]], dtype=float32)