In [141]:
import pandas as pd

In [142]:
dataset = pd.read_csv("target_tabungan.csv")

In [143]:
dataset.head()

,tanggal,nama_target_id,nama_target,jumlah_target,nabung_harian,jumlah_terkumpul,progres,sisa_target,status_id,status
0,01/01/2022,0,Iphone 17 Pro Max,25000000,300000,300000,0.01,0.99,0,BELUM TERPENUHI
1,01/02/2022,0,Iphone 17 Pro Max,25000000,500000,800000,0.03,0.97,0,BELUM TERPENUHI
2,01/03/2022,0,Iphone 17 Pro Max,25000000,200000,1000000,0.04,0.96,0,BELUM TERPENUHI
3,01/04/2022,0,Iphone 17 Pro Max,25000000,500000,1500000,0.06,0.94,0,BELUM TERPENUHI
4,01/05/2022,0,Iphone 17 Pro Max,25000000,500000,2000000,0.08,0.92,0,BELUM TERPENUHI

In [144]:
dataset['tanggal'] = pd.to_datetime(dataset['tanggal'])

finish_dates = (
    dataset[dataset['status_id'] == 1]
    .groupby('nama_target_id')['tanggal']
    .max()
)

dataset['finish_date'] = dataset['nama_target_id'].map(finish_dates)

dataset['remaining_days'] = (
    dataset['finish_date'] - dataset['tanggal']
).dt.days

df = dataset[['tanggal', 'jumlah_target', 'nabung_harian', 'jumlah_terkumpul', 'status_id', 'remaining_days']].copy()

df['estimated_days_formula'] = (
    (df['jumlah_target'] - df['jumlah_terkumpul']) /
    df['nabung_harian']
)

df['tabungan_h1'] = (
    df['nabung_harian']
    .shift(1)
    .fillna(0)
)

df['tabungan_h2'] = (
    df['nabung_harian']
    .shift(2)
    .fillna(0)
)

df['tabungan_h3'] = (
    df['nabung_harian']
    .shift(3)
    .fillna(0)
)

df['avg_3d'] = (
    df[['tabungan_h1', 'tabungan_h2', 'tabungan_h3']]
    .mean(axis=1)
)

df['trend_3d'] = (
    df['tabungan_h1'] -
    df['tabungan_h3']
)

df

,tanggal,jumlah_target,nabung_harian,jumlah_terkumpul,status_id,remaining_days,estimated_days_formula,tabungan_h1,tabungan_h2,tabungan_h3,avg_3d,trend_3d
0,2022-01-01,25000000,300000,300000,0,106,82.333333,0.0,0.0,0.0,0.000000,0.0
1,2022-01-02,25000000,500000,800000,0,105,48.400000,300000.0,0.0,0.0,100000.000000,300000.0
2,2022-01-03,25000000,200000,1000000,0,104,120.000000,500000.0,300000.0,0.0,266666.666667,500000.0
3,2022-01-04,25000000,500000,1500000,0,103,47.000000,200000.0,500000.0,300000.0,333333.333333,-100000.0
4,2022-01-05,25000000,500000,2000000,0,102,46.000000,500000.0,200000.0,500000.0,400000.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1206,2025-04-21,8000000,300000,6750000,0,4,4.166667,500000.0,200000.0,50000.0,250000.000000,450000.0
1207,2025-04-22,8000000,200000,6950000,0,3,5.250000,300000.0,500000.0,200000.0,333333.333333,100000.0
1208,2025-04-23,8000000,100000,7050000,0,2,9.500000,200000.0,300000.0,500000.0,333333.333333,-300000.0
1209,2025-04-24,8000000,500000,7550000,0,1,0.900000,100000.0,200000.0,300000.0,200000.000000,-200000.0
1210,2025-04-25,8000000,500000,8050000,1,0,-0.100000,500000.0,100000.0,200000.0,266666.666667,300000.0

In [145]:
from sklearn.model_selection import train_test_split

X = df[
    [
        'jumlah_target',
        'jumlah_terkumpul',
        'nabung_harian',
        'estimated_days_formula',
        'tabungan_h1',
        'tabungan_h2',
        'tabungan_h3',
        'avg_3d',
        'trend_3d'
    ]
]

y = df['remaining_days']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [146]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [147]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

inputs = tf.keras.Input(shape=(X_train.shape[1],))

x = Dense(128, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
x = Dense(32, activation='relu')(x)

outputs = Dense(1)(x)

model = Model(inputs, outputs)

model.compile(
    optimizer='adam',
    loss='mae',
    metrics=['mae']
)

In [148]:
class StopAtMAE(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        mae = logs.get('mae')

        if mae < 0.03:
            self.model.stop_training = True

In [149]:
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[StopAtMAE()]
)

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 55.0427 - mae: 55.0427 - val_loss: 55.5926 - val_mae: 55.5926
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.1115 - mae: 50.1115 - val_loss: 46.6485 - val_mae: 46.6485
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.2031 - mae: 39.2031 - val_loss: 31.9552 - val_mae: 31.9552
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.0637 - mae: 27.0637 - val_loss: 22.1531 - val_mae: 22.1531
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.5243 - mae: 20.5243 - val_loss: 17.1496 - val_mae: 17.1496
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.4876 - mae: 16.4876 - val_loss: 12.8341 - val_mae: 12.8341
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.6870 - mae: 12.6870 - val_loss: 10.2534 - val_mae: 10.2534
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4443 - mae: 10.4443 - val_loss: 8.8885 - val_mae: 8.8885
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8332 - mae: 8.8332 - val_loss: 7.9264 - val_mae: 7.9264
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.6570 - mae: 7.6570 - val_loss: 7.4039 - val_mae: 7.4039
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8836 - mae: 6.8836 - val_loss: 6.5415 - val_mae: 6.5415
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.1375 - mae: 6.1375 - val_loss: 6.4537 - val_mae: 6.4537
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.7373 - mae: 5.7373 - val_loss: 5.7045 - val_mae: 5.7045
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.2345 - mae: 5.2345 - val_loss: 5.3858 - val_mae: 5.3858
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.7129 - mae: 4.7129 - val_loss: 4.7255 - val_mae: 4.7255
Epoch 16/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.4778 - mae: 4.4778 - val_loss: 4.7119 - val_mae: 4.7119
Epoch 17/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.2110 - mae: 4.2110 - val_loss: 4.2884 - val_mae: 4.2884
Epoch 18/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.8636 - mae: 3.8636 - val_loss: 4.1479 - val_mae: 4.1479
Epoch 19/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.7280 - mae: 3.7280 - val_loss: 3.8976 - val_mae: 3.8976
Epoch 20/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.4931 - mae: 3.4931 - val_loss: 3.9142 - val_mae: 3.9142
Epoch 21/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.5683 - mae: 3.5683 - val_loss: 3.7878 - val_mae: 3.7878
Epoch 22/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3367 - mae: 3.3367 - val_loss: 3.7287 - val_mae: 3.7287
Epoch 23/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.2496 - mae: 3.2496 - val_loss: 3.9155 - val_mae: 3.9155
Epoch 24/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.2802 - mae: 3.2802 - val_loss: 3.5479 - val_mae: 3.5479
Epoch 25/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.1453 - mae: 3.1453 - val_loss: 3.6476 - val_mae: 3.6476
Epoch 26/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.3511 - mae: 3.3511 - val_loss: 3.6561 - val_mae: 3.6561
Epoch 27/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.1716 - mae: 3.1716 - val_loss: 3.7268 - val_mae: 3.7268
Epoch 28/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.1573 - mae: 3.1573 - val_loss: 3.4304 - val_mae: 3.4304
Epoch 29/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.1168 - mae: 3.1168 - val_loss: 3.4213 - val_mae: 3.4213
Epoch 30/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1931 - mae: 3.1931 - val_loss: 3.5911 - val_mae: 3.5911
Epoch 31/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.1285 - mae: 3.1285 - val_loss: 3.6060 - val_mae: 3.6060
Epoch 32/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.2327 - mae: 3.2327 - val_loss: 3.5059 - val_mae: 3.5059
Epoch 33/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.0469 - mae: 3.0469 - val_loss: 3.5688 - val_mae: 3.5688
Epoch 34/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.9149 - mae: 2.9149 - val_loss: 3.6255 - val_mae: 3.6255
Epoch 35/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.0188 - mae: 3.0188 - val_loss: 3.7371 - val_mae: 3.7371
Epoch 36/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8850 - mae: 2.8850 - val_loss: 3.6211 - val_mae: 3.6211
Epoch 37/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9192 - mae: 2.9192 - val_loss: 3.5495 - val_mae: 3.5495
Epoch 38/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8769 - mae: 2.8769 - val_loss: 3.6272 - val_mae: 3.6272
Epoch 39/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9524 - mae: 2.9524 - val_loss: 3.6407 - val_mae: 3.6407
Epoch 40/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8251 - mae: 2.8251 - val_loss: 3.5899 - val_mae: 3.5899
Epoch 41/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8812 - mae: 2.8812 - val_loss: 3.3921 - val_mae: 3.3921
Epoch 42/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7690 - mae: 2.7690 - val_loss: 3.5010 - val_mae: 3.5010
Epoch 43/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8066 - mae: 2.8066 - val_loss: 3.5646 - val_mae: 3.5646
Epoch 44/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8720 - mae: 2.8720 - val_loss: 3.4075 - val_mae: 3.4075
Epoch 45/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7783 - mae: 2.7783 - val_loss: 3.4398 - val_mae: 3.4398
Epoch 46/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7369 - mae: 2.7369 - val_loss: 3.4406 - val_mae: 3.4406
Epoch 47/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7695 - mae: 2.7695 - val_loss: 3.3239 - val_mae: 3.3239
Epoch 48/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7085 - mae: 2.7085 - val_loss: 3.3437 - val_mae: 3.3437
Epoch 49/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8378 - mae: 2.8378 - val_loss: 3.4179 - val_mae: 3.4179
Epoch 50/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8670 - mae: 2.8670 - val_loss: 3.7540 - val_mae: 3.7540
Epoch 51/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9612 - mae: 2.9612 - val_loss: 3.2845 - val_mae: 3.2845
Epoch 52/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.7107 - mae: 2.7107 - val_loss: 3.3086 - val_mae: 3.3086
Epoch 53/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7910 - mae: 2.7910 - val_loss: 3.5168 - val_mae: 3.5168
Epoch 54/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7652 - mae: 2.7652 - val_loss: 3.5029 - val_mae: 3.5029
Epoch 55/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6831 - mae: 2.6831 - val_loss: 3.7197 - val_mae: 3.7197
Epoch 56/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9237 - mae: 2.9237 - val_loss: 3.7313 - val_mae: 3.7313
Epoch 57/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7289 - mae: 2.7289 - val_loss: 3.6056 - val_mae: 3.6056
Epoch 58/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7350 - mae: 2.7350 - val_loss: 3.4204 - val_mae: 3.4204
Epoch 59/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7515 - mae: 2.7515 - val_loss: 3.4018 - val_mae: 3.4018
Epoch 60/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7019 - mae: 2.7019 - val_loss: 3.3392 - val_mae: 3.3392
Epoch 61/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5697 - mae: 2.5697 - val_loss: 3.2605 - val_mae: 3.2605
Epoch 62/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6519 - mae: 2.6519 - val_loss: 3.5332 - val_mae: 3.5332
Epoch 63/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8401 - mae: 2.8401 - val_loss: 3.7129 - val_mae: 3.7129
Epoch 64/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7067 - mae: 2.7067 - val_loss: 3.4215 - val_mae: 3.4215
Epoch 65/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6475 - mae: 2.6475 - val_loss: 3.2921 - val_mae: 3.2921
Epoch 66/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5573 - mae: 2.5573 - val_loss: 3.4558 - val_mae: 3.4558
Epoch 67/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6433 - mae: 2.6433 - val_loss: 3.5115 - val_mae: 3.5115
Epoch 68/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6613 - mae: 2.6613 - val_loss: 3.3439 - val_mae: 3.3439
Epoch 69/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5472 - mae: 2.5472 - val_loss: 3.3683 - val_mae: 3.3683
Epoch 70/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5130 - mae: 2.5130 - val_loss: 3.2212 - val_mae: 3.2212
Epoch 71/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5174 - mae: 2.5174 - val_loss: 3.4798 - val_mae: 3.4798
Epoch 72/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6008 - mae: 2.6008 - val_loss: 3.3044 - val_mae: 3.3044
Epoch 73/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5265 - mae: 2.5265 - val_loss: 3.3420 - val_mae: 3.3420
Epoch 74/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5602 - mae: 2.5602 - val_loss: 3.3782 - val_mae: 3.3782
Epoch 75/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5842 - mae: 2.5842 - val_loss: 3.2538 - val_mae: 3.2538
Epoch 76/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.5156 - mae: 2.5156 - val_loss: 3.2264 - val_mae: 3.2264
Epoch 77/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.5896 - mae: 2.5896 - val_loss: 3.2606 - val_mae: 3.2606
Epoch 78/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.4812 - mae: 2.4812 - val_loss: 3.3330 - val_mae: 3.3330
Epoch 79/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.4758 - mae: 2.4758 - val_loss: 3.3275 - val_mae: 3.3275
Epoch 80/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.5241 - mae: 2.5241 - val_loss: 3.2220 - val_mae: 3.2220
Epoch 81/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.4738 - mae: 2.4738 - val_loss: 3.3517 - val_mae: 3.3517
Epoch 82/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.5027 - mae: 2.5027 - val_loss: 3.3238 - val_mae: 3.3238
Epoch 83/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5168 - mae: 2.5168 - val_loss: 3.3483 - val_mae: 3.3483
Epoch 84/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5547 - mae: 2.5547 - val_loss: 3.3043 - val_mae: 3.3043
Epoch 85/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4260 - mae: 2.4260 - val_loss: 3.2534 - val_mae: 3.2534
Epoch 86/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4738 - mae: 2.4738 - val_loss: 3.3769 - val_mae: 3.3769
Epoch 87/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4033 - mae: 2.4033 - val_loss: 3.2428 - val_mae: 3.2428
Epoch 88/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5183 - mae: 2.5183 - val_loss: 3.2502 - val_mae: 3.2502
Epoch 89/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5515 - mae: 2.5515 - val_loss: 3.3064 - val_mae: 3.3064
Epoch 90/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4841 - mae: 2.4841 - val_loss: 3.2391 - val_mae: 3.2391
Epoch 91/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4472 - mae: 2.4472 - val_loss: 3.3067 - val_mae: 3.3067
Epoch 92/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4518 - mae: 2.4518 - val_loss: 3.2657 - val_mae: 3.2657
Epoch 93/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4455 - mae: 2.4455 - val_loss: 3.3366 - val_mae: 3.3366
Epoch 94/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4098 - mae: 2.4098 - val_loss: 3.3542 - val_mae: 3.3542
Epoch 95/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5016 - mae: 2.5016 - val_loss: 3.3257 - val_mae: 3.3257
Epoch 96/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7234 - mae: 2.7234 - val_loss: 3.3007 - val_mae: 3.3007
Epoch 97/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6964 - mae: 2.6964 - val_loss: 3.1732 - val_mae: 3.1732
Epoch 98/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.3873 - mae: 2.3873 - val_loss: 3.1983 - val_mae: 3.1983
Epoch 99/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4254 - mae: 2.4254 - val_loss: 3.5009 - val_mae: 3.5009
Epoch 100/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.4706 - mae: 2.4706 - val_loss: 3.5071 - val_mae: 3.5071

In [150]:
loss, mae = model.evaluate(X_test, y_test)

print("MAE:", mae)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5505 - mae: 3.5505
MAE: 3.5504939556121826

In [151]:
pred = model.predict(X_test)

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': pred.flatten()
})

comparison.head(10)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

   Actual   Predicted
0       5    4.353425
1     131  131.213928
2      19   17.724783
3     129  123.692833
4      30   31.082136
5      55   51.795418
6      21   20.806288
7      57   58.886066
8      38   38.945076
9      40   43.293266

In [152]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, pred)

print("R2 Score:", r2)

R2 Score: 0.9827653765678406

In [153]:
model.export("SavedModel")

Saved artifact at 'SavedModel'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 9), dtype=tf.float32, name='keras_tensor_25')
Output Type:
  TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)
Captures:
  132522422454224: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132522422463440: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132522422456336: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132522422455376: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132522422457872: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132522422462672: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132522422453456: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132522422460560: TensorSpec(shape=(), dtype=tf.resource, name=None)

In [154]:
from google.colab import files
import shutil
import os

shutil.make_archive("SavedModel", 'zip', "SavedModel")
files.download("SavedModel.zip")

In [155]:
import joblib

joblib.dump(scaler, 'scaler.save')

['scaler.save']

Inference

In [158]:
def predict_saving_days(
    jumlah_target,
    jumlah_terkumpul,
    nabung_harian,
    tabungan_h1=0,
    tabungan_h2=0,
    tabungan_h3=0
):

    avg_3d = (
        tabungan_h1 +
        tabungan_h2 +
        tabungan_h3
    ) / 3

    if avg_3d == 0:
        avg_3d = nabung_harian

    trend_3d = (
        tabungan_h1 -
        tabungan_h3
    )

    sisa_target = max(
        jumlah_target - jumlah_terkumpul,
        0
    )

    estimated_days_formula = (
        sisa_target / avg_3d
    )

    if estimated_days_formula <= 7:
        return estimated_days_formula

    new_data = pd.DataFrame({
        'jumlah_target': [jumlah_target],
        'jumlah_terkumpul': [jumlah_terkumpul],
        'nabung_harian': [nabung_harian],
        'estimated_days_formula': [estimated_days_formula],
        'tabungan_h1': [tabungan_h1],
        'tabungan_h2': [tabungan_h2],
        'tabungan_h3': [tabungan_h3],
        'avg_3d': [avg_3d],
        'trend_3d': [trend_3d]
    })

    new_data_scaled = scaler.transform(new_data)

    ml_prediction = model.predict(
        new_data_scaled,
        verbose=0
    )[0][0]

    final_prediction = (
        estimated_days_formula * 0.5 +
        ml_prediction * 0.5
    )

    return max(final_prediction, 0)

In [159]:
test_cases = [
    {
        "name": "CASE 1 - Normal Stabil",
        "args": (
            30000000,
            15000000,
            200000,
            180000,
            200000,
            220000
        )
    },

    {
        "name": "CASE 2 - Makin Rajin",
        "args": (
            25000000,
            10000000,
            300000,
            200000,
            400000,
            700000
        )
    },

    {
        "name": "CASE 3 - Mulai Males",
        "args": (
            25000000,
            10000000,
            300000,
            300000,
            100000,
            0
        )
    },

    {
        "name": "CASE 4 - Hampir Selesai",
        "args": (
            10000000,
            9500000,
            100000,
            100000,
            100000,
            100000
        )
    },

    {
        "name": "CASE 5 - Super Rajin",
        "args": (
            50000000,
            30000000,
            1000000,
            700000,
            900000,
            1200000
        )
    },

    {
        "name": "CASE 6 - Cold Start",
        "args": (
            15000000,
            1000000,
            150000,
            0,
            0,
            0
        )
    },

    {
        "name": "CASE 7 - Extreme Kecil",
        "args": (
            20000000,
            1000000,
            10000,
            5000,
            10000,
            15000
        )
    }
]

for case in test_cases:
    prediction = predict_saving_days(*case["args"])

    print("=" * 50)
    print(case["name"])
    print(f"Prediction : {prediction:.2f} hari")

==================================================
CASE 1 - Normal Stabil
Prediction : 70.14 hari
==================================================
CASE 2 - Makin Rajin
Prediction : 53.18 hari
==================================================
CASE 3 - Mulai Males
Prediction : 88.06 hari
==================================================
CASE 4 - Hampir Selesai
Prediction : 5.00 hari
==================================================
CASE 5 - Super Rajin
Prediction : 54.42 hari
==================================================
CASE 6 - Cold Start
Prediction : 75.31 hari
==================================================
CASE 7 - Extreme Kecil
Prediction : 1035.09 hari