In [3]:
import pandas as pd

In [4]:
dataset = pd.read_csv("target_tabungan.csv")

In [5]:
dataset.head()

,tanggal,nama_target_id,nama_target,jumlah_target,nabung_harian,jumlah_terkumpul,progres,sisa_target,status_id,status
0,01/01/2022,0,Iphone 17 Pro Max,25000000,300000,300000,0.01,0.99,0,BELUM TERPENUHI
1,01/02/2022,0,Iphone 17 Pro Max,25000000,500000,800000,0.03,0.97,0,BELUM TERPENUHI
2,01/03/2022,0,Iphone 17 Pro Max,25000000,200000,1000000,0.04,0.96,0,BELUM TERPENUHI
3,01/04/2022,0,Iphone 17 Pro Max,25000000,500000,1500000,0.06,0.94,0,BELUM TERPENUHI
4,01/05/2022,0,Iphone 17 Pro Max,25000000,500000,2000000,0.08,0.92,0,BELUM TERPENUHI

In [6]:
dataset['tanggal'] = pd.to_datetime(dataset['tanggal'])

finish_dates = (
    dataset[dataset['status_id'] == 1]
    .groupby('nama_target_id')['tanggal']
    .max()
)

dataset['finish_date'] = dataset['nama_target_id'].map(finish_dates)

dataset['remaining_days'] = (
    dataset['finish_date'] - dataset['tanggal']
).dt.days

df = dataset[['tanggal', 'jumlah_target', 'nabung_harian', 'jumlah_terkumpul', 'status_id', 'remaining_days']].copy()
df

,tanggal,jumlah_target,nabung_harian,jumlah_terkumpul,status_id,remaining_days
0,2022-01-01,25000000,300000,300000,0,106
1,2022-01-02,25000000,500000,800000,0,105
2,2022-01-03,25000000,200000,1000000,0,104
3,2022-01-04,25000000,500000,1500000,0,103
4,2022-01-05,25000000,500000,2000000,0,102
...,...,...,...,...,...,...
1206,2025-04-21,8000000,300000,6750000,0,4
1207,2025-04-22,8000000,200000,6950000,0,3
1208,2025-04-23,8000000,100000,7050000,0,2
1209,2025-04-24,8000000,500000,7550000,0,1
1210,2025-04-25,8000000,500000,8050000,1,0

In [7]:
from sklearn.model_selection import train_test_split

X = df[
    [
        'jumlah_target',
        'nabung_harian',
        'jumlah_terkumpul'
    ]
]

y = df['remaining_days']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

inputs = tf.keras.Input(shape=(X_train.shape[1],))

x = Dense(128, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
x = Dense(32, activation='relu')(x)

outputs = Dense(1)(x)

model = Model(inputs, outputs)

model.compile(
    optimizer='adam',
    loss='mae',
    metrics=['mae']
)

In [10]:
class StopAtMAE(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        mae = logs.get('mae')

        if mae < 0.03:
            self.model.stop_training = True

In [11]:
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[StopAtMAE()]
)

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 55.1739 - mae: 55.1739 - val_loss: 56.2602 - val_mae: 56.2602
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 51.6995 - mae: 51.6995 - val_loss: 49.3127 - val_mae: 49.3127
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 43.0661 - mae: 43.0661 - val_loss: 36.0344 - val_mae: 36.0344
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.8944 - mae: 28.8944 - val_loss: 17.1713 - val_mae: 17.1713
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.7398 - mae: 15.7398 - val_loss: 11.0434 - val_mae: 11.0434
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.2394 - mae: 10.2394 - val_loss: 8.5622 - val_mae: 8.5622
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.9779 - mae: 7.9779 - val_loss: 7.1931 - val_mae: 7.1931
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5280 - mae: 6.5280 - val_loss: 5.9466 - val_mae: 5.9466
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.3850 - mae: 5.3850 - val_loss: 4.9621 - val_mae: 4.9621
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.4592 - mae: 4.4592 - val_loss: 4.1065 - val_mae: 4.1065
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.8567 - mae: 3.8567 - val_loss: 3.7199 - val_mae: 3.7199
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.4420 - mae: 3.4420 - val_loss: 3.4285 - val_mae: 3.4285
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.2251 - mae: 3.2251 - val_loss: 3.4601 - val_mae: 3.4601
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.1272 - mae: 3.1272 - val_loss: 3.2410 - val_mae: 3.2410
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.0819 - mae: 3.0819 - val_loss: 3.2971 - val_mae: 3.2971
Epoch 16/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.0417 - mae: 3.0417 - val_loss: 3.2947 - val_mae: 3.2947
Epoch 17/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.0909 - mae: 3.0909 - val_loss: 3.3665 - val_mae: 3.3665
Epoch 18/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.0433 - mae: 3.0433 - val_loss: 3.4851 - val_mae: 3.4851
Epoch 19/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9544 - mae: 2.9544 - val_loss: 3.3158 - val_mae: 3.3158
Epoch 20/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.0225 - mae: 3.0225 - val_loss: 3.4650 - val_mae: 3.4650
Epoch 21/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9980 - mae: 2.9980 - val_loss: 3.2169 - val_mae: 3.2169
Epoch 22/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9444 - mae: 2.9444 - val_loss: 3.1930 - val_mae: 3.1930
Epoch 23/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9508 - mae: 2.9508 - val_loss: 3.3942 - val_mae: 3.3942
Epoch 24/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8924 - mae: 2.8924 - val_loss: 3.1513 - val_mae: 3.1513
Epoch 25/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8370 - mae: 2.8370 - val_loss: 3.1538 - val_mae: 3.1538
Epoch 26/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9163 - mae: 2.9163 - val_loss: 3.1774 - val_mae: 3.1774
Epoch 27/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9594 - mae: 2.9594 - val_loss: 3.1368 - val_mae: 3.1368
Epoch 28/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8731 - mae: 2.8731 - val_loss: 3.1289 - val_mae: 3.1289
Epoch 29/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8702 - mae: 2.8702 - val_loss: 3.1582 - val_mae: 3.1582
Epoch 30/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8915 - mae: 2.8915 - val_loss: 3.2606 - val_mae: 3.2606
Epoch 31/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8551 - mae: 2.8551 - val_loss: 3.0834 - val_mae: 3.0834
Epoch 32/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8724 - mae: 2.8724 - val_loss: 3.0567 - val_mae: 3.0567
Epoch 33/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8405 - mae: 2.8405 - val_loss: 3.0976 - val_mae: 3.0976
Epoch 34/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8540 - mae: 2.8540 - val_loss: 3.0288 - val_mae: 3.0288
Epoch 35/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8375 - mae: 2.8375 - val_loss: 3.1172 - val_mae: 3.1172
Epoch 36/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8172 - mae: 2.8172 - val_loss: 3.1378 - val_mae: 3.1378
Epoch 37/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7857 - mae: 2.7857 - val_loss: 3.1589 - val_mae: 3.1589
Epoch 38/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7685 - mae: 2.7685 - val_loss: 3.0651 - val_mae: 3.0651
Epoch 39/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7413 - mae: 2.7413 - val_loss: 3.1261 - val_mae: 3.1261
Epoch 40/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8723 - mae: 2.8723 - val_loss: 3.1631 - val_mae: 3.1631
Epoch 41/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8120 - mae: 2.8120 - val_loss: 3.1836 - val_mae: 3.1836
Epoch 42/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9425 - mae: 2.9425 - val_loss: 3.1421 - val_mae: 3.1421
Epoch 43/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7559 - mae: 2.7559 - val_loss: 3.0347 - val_mae: 3.0347
Epoch 44/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7146 - mae: 2.7146 - val_loss: 3.0174 - val_mae: 3.0174
Epoch 45/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8536 - mae: 2.8536 - val_loss: 3.4388 - val_mae: 3.4388
Epoch 46/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7317 - mae: 2.7317 - val_loss: 3.0672 - val_mae: 3.0672
Epoch 47/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7616 - mae: 2.7616 - val_loss: 3.0052 - val_mae: 3.0052
Epoch 48/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7185 - mae: 2.7185 - val_loss: 3.5309 - val_mae: 3.5309
Epoch 49/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9731 - mae: 2.9731 - val_loss: 3.0592 - val_mae: 3.0592
Epoch 50/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8071 - mae: 2.8071 - val_loss: 2.9514 - val_mae: 2.9514
Epoch 51/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6753 - mae: 2.6753 - val_loss: 2.9327 - val_mae: 2.9327
Epoch 52/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7902 - mae: 2.7902 - val_loss: 2.9664 - val_mae: 2.9664
Epoch 53/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7471 - mae: 2.7471 - val_loss: 2.9587 - val_mae: 2.9587
Epoch 54/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7410 - mae: 2.7410 - val_loss: 2.9340 - val_mae: 2.9340
Epoch 55/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6991 - mae: 2.6991 - val_loss: 2.9449 - val_mae: 2.9449
Epoch 56/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7126 - mae: 2.7126 - val_loss: 3.0363 - val_mae: 3.0363
Epoch 57/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6766 - mae: 2.6766 - val_loss: 3.1000 - val_mae: 3.1000
Epoch 58/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6777 - mae: 2.6777 - val_loss: 2.9933 - val_mae: 2.9933
Epoch 59/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6326 - mae: 2.6326 - val_loss: 2.9943 - val_mae: 2.9943
Epoch 60/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6835 - mae: 2.6835 - val_loss: 2.9016 - val_mae: 2.9016
Epoch 61/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6537 - mae: 2.6537 - val_loss: 2.9991 - val_mae: 2.9991
Epoch 62/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7443 - mae: 2.7443 - val_loss: 2.9442 - val_mae: 2.9442
Epoch 63/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6613 - mae: 2.6613 - val_loss: 2.9070 - val_mae: 2.9070
Epoch 64/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6301 - mae: 2.6301 - val_loss: 2.9071 - val_mae: 2.9071
Epoch 65/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6042 - mae: 2.6042 - val_loss: 2.9297 - val_mae: 2.9297
Epoch 66/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6525 - mae: 2.6525 - val_loss: 2.9218 - val_mae: 2.9218
Epoch 67/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5985 - mae: 2.5985 - val_loss: 3.0449 - val_mae: 3.0449
Epoch 68/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6284 - mae: 2.6284 - val_loss: 2.9738 - val_mae: 2.9738
Epoch 69/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6586 - mae: 2.6586 - val_loss: 2.9456 - val_mae: 2.9456
Epoch 70/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6274 - mae: 2.6274 - val_loss: 3.0323 - val_mae: 3.0323
Epoch 71/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6289 - mae: 2.6289 - val_loss: 2.9604 - val_mae: 2.9604
Epoch 72/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7559 - mae: 2.7559 - val_loss: 3.1004 - val_mae: 3.1004
Epoch 73/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7123 - mae: 2.7123 - val_loss: 2.9007 - val_mae: 2.9007
Epoch 74/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6903 - mae: 2.6903 - val_loss: 3.0353 - val_mae: 3.0353
Epoch 75/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7702 - mae: 2.7702 - val_loss: 2.9810 - val_mae: 2.9810
Epoch 76/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8083 - mae: 2.8083 - val_loss: 2.9338 - val_mae: 2.9338
Epoch 77/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7326 - mae: 2.7326 - val_loss: 2.9688 - val_mae: 2.9688
Epoch 78/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6003 - mae: 2.6003 - val_loss: 2.9433 - val_mae: 2.9433
Epoch 79/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5867 - mae: 2.5867 - val_loss: 2.8950 - val_mae: 2.8950
Epoch 80/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5543 - mae: 2.5543 - val_loss: 2.9330 - val_mae: 2.9330
Epoch 81/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5858 - mae: 2.5858 - val_loss: 2.8883 - val_mae: 2.8883
Epoch 82/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5589 - mae: 2.5589 - val_loss: 2.8842 - val_mae: 2.8842
Epoch 83/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6594 - mae: 2.6594 - val_loss: 2.8919 - val_mae: 2.8919
Epoch 84/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6189 - mae: 2.6189 - val_loss: 3.1551 - val_mae: 3.1551
Epoch 85/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6239 - mae: 2.6239 - val_loss: 2.9503 - val_mae: 2.9503
Epoch 86/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5649 - mae: 2.5649 - val_loss: 2.8967 - val_mae: 2.8967
Epoch 87/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7616 - mae: 2.7616 - val_loss: 3.0984 - val_mae: 3.0984
Epoch 88/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5986 - mae: 2.5986 - val_loss: 2.9309 - val_mae: 2.9309
Epoch 89/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.6379 - mae: 2.6379 - val_loss: 3.1876 - val_mae: 3.1876
Epoch 90/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5951 - mae: 2.5951 - val_loss: 2.8670 - val_mae: 2.8670
Epoch 91/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5746 - mae: 2.5746 - val_loss: 3.0426 - val_mae: 3.0426
Epoch 92/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5851 - mae: 2.5851 - val_loss: 2.9057 - val_mae: 2.9057
Epoch 93/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7282 - mae: 2.7282 - val_loss: 2.8426 - val_mae: 2.8426
Epoch 94/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5642 - mae: 2.5642 - val_loss: 2.8883 - val_mae: 2.8883
Epoch 95/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6306 - mae: 2.6306 - val_loss: 2.8904 - val_mae: 2.8904
Epoch 96/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7775 - mae: 2.7775 - val_loss: 3.1207 - val_mae: 3.1207
Epoch 97/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6115 - mae: 2.6115 - val_loss: 2.8484 - val_mae: 2.8484
Epoch 98/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6152 - mae: 2.6152 - val_loss: 2.8455 - val_mae: 2.8455
Epoch 99/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6351 - mae: 2.6351 - val_loss: 2.9607 - val_mae: 2.9607
Epoch 100/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5558 - mae: 2.5558 - val_loss: 2.8832 - val_mae: 2.8832

In [12]:
loss, mae = model.evaluate(X_test, y_test)

print("MAE:", mae)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.8188 - mae: 2.8188
MAE: 2.818781614303589

In [13]:
pred = model.predict(X_test)

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': pred.flatten()
})

comparison.head(10)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

   Actual   Predicted
0       5    4.662065
1     131  130.056992
2      19   21.232552
3     129  125.239754
4      30   30.884085
5      55   54.251263
6      21   21.391649
7      57   57.768658
8      38   35.864758
9      40   43.851906

In [14]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, pred)

print("R2 Score:", r2)

R2 Score: 0.987911581993103

In [21]:
model.save("model_tabungan.keras")

In [ ]:
from google.colab import drive
import shutil

drive.mount('/content/drive')

shutil.copy('model_tabungan.keras', '/content/drive/MyDrive/model_tabungan.keras')

Mounted at /content/drive

'/content/drive/MyDrive/model_tabungan.keras'

Inference

In [18]:
new_data = pd.DataFrame({
    'jumlah_target': [28000000],
    'nabung_harian': [100000],
    'jumlah_terkumpul': [1000000],
})

new_data_scaled = scaler.transform(new_data)

prediction = model.predict(new_data_scaled)

prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

array([[124.42208]], dtype=float32)